### ISSUE TITLE
Test File `val_data`

### ISSUE THREAD

**Issue by fujistoo** [sndnyang/imagenet64x64#2]
What is this `val_data` mentioned in your `ipynb`? Can't seem to find it anywhere.

**Comment by sndnyang** [comment]
Eh,  you should download the dataset  https://github.com/PatrykChrabaszcz/Imagenet32_Scripts  ,   ImageNet has 2 directories "train" and "val",  downsampled ImageNet also uses the same name.

**Comment by fujistoo** [comment]
Gotcha.
